### ISSUE TITLE
add bond network support

### ISSUE THREAD

**Issue by borball** [borball/mno-with-abi#4]
```
hosts:
  common:
    bond:
      mode: 802.3ad
      
  masters:
    - interface: bond0
      bond:
        members:
          - interface: ens1f0
            mac: 10:16:b7:2a:67:60
          - interface: ens1f
            mac: 10:16:b7:2a:67:61
```
